name: Pre-release Testing

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@master

  release:
    name: Prepare the release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Create a release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
